#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
hour=0
minute=1

while [$hour -lt 13 ]
do
	[$minutes -lt 60 ]
do
	printf "%02d : %02d\n" $hour $minute
	minute=$((minute + 1))
done
	hour=$((hour + 1))
	minute=0
done
