#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes

#display hours 0 to 12 
#display miunutes from 1 to 59

h=0

while [ $h -le 13 ]
do 
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		(( minute++ ))
	done
	(( hour++ ))
done 
