#!/usr/bin/env bash
#This is how you manage a file

JUICE=/var/run/my_process.pid

case "$1" in
    start)
        bash manage_my_process &
        echo $! > $JUICE
        echo "manage_my_process started"
        ;;
    stop)
        kill "$(cat $JUICE)"
        rm $JUICE
        echo "manage_my_process stopped"
        ;;
restart)
        kill "$(cat $JUICE)"
        rm "$JUICE"
        bash manage_my_process &
        echo $! > $JUICE
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

